# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
use_frameworks!

target 'Donate' do

pod 'Stripe', '~> 4.0'
pod 'AFNetworking', '~> 2.5.4'

end

target 'DonateTests' do

end

